### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by azzamsa** [kindista/kindista#2]
@endlessbeing Thank you for this great web apps.
This one is  great web app that I visit when I want to know how to implement something in Common Lisp web.

It's a pleasure if you blog about building web apps with Common Lisp.

Thank you so much.

*I think this is the only open source/free software CL web app out there*

**Comment by endlessbeing** [comment]
I happy this has been valuable for you. I do not intend to write a blog about web app development with common lisp. I'm happy to answer questions though.

**Comment by azzamsa** [comment]
Sure thank you. I will reach you when I need help :)
